image: node:20

stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

pages:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
